field: c60c2474-7439-41cd-85f5-6e4cae7dd248 # Contentbuilder
fieldLayouts:
  5066e942-a9ba-4e7e-a23e-52aada24aae7:
    tabs:
      -
        elements:
          -
            fieldUid: 339abcb4-a057-493b-b476-f0e97109e503 # Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9ec79e0e-84e8-4fda-a864-4178e617f58f # Tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fb51647c-616d-42e6-a5e3-9d666755ef78 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cc7d51c5-63b8-4815-a43e-fbaa97aa29e5 # Afbeelding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 3a54b8a0-7fe7-4a7c-8b7a-e04d4de00b09 # Uitlijning afbeelding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  3a54b8a0-7fe7-4a7c-8b7a-e04d4de00b09: # Uitlijning afbeelding
    contentColumnType: boolean
    fieldGroup: null
    handle: uitlijningAfbeelding
    instructions: ''
    name: 'Uitlijning afbeelding'
    searchable: false
    settings:
      default: false
      offLabel: Rechts
      onLabel: Links
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  9ec79e0e-84e8-4fda-a864-4178e617f58f: # Tekst
    contentColumnType: text
    fieldGroup: null
    handle: tekst
    instructions: ''
    name: Tekst
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: SimpleLink.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  339abcb4-a057-493b-b476-f0e97109e503: # Titel
    contentColumnType: text
    fieldGroup: null
    handle: titel
    instructions: ''
    name: Titel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cc7d51c5-63b8-4815-a43e-fbaa97aa29e5: # Afbeelding
    contentColumnType: string
    fieldGroup: null
    handle: afbeelding
    instructions: ''
    name: Afbeelding
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:0ec915c7-18b6-48c5-b39e-cdb91912dff1'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: 'Voeg een afbeelding toe'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:fec35df0-28e8-4c43-a351-739f588f7de7'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:fec35df0-28e8-4c43-a351-739f588f7de7'
        - 'volume:0ec915c7-18b6-48c5-b39e-cdb91912dff1'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  fb51647c-616d-42e6-a5e3-9d666755ef78: # Button
    contentColumnType: text
    fieldGroup: null
    handle: button
    instructions: ''
    name: Button
    searchable: false
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        1: asset
        4: entry
        6: custom
        7: email
        8: tel
        9: url
      autoNoReferrer: ''
      defaultLinkName: entry
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: typedlinkfield\fields\LinkField
handle: afbeeldingTekst
name: 'Afbeelding + tekst'
sortOrder: 1
