field: c60c2474-7439-41cd-85f5-6e4cae7dd248 # Contentbuilder
fieldLayouts:
  8c7438ad-4bed-418b-a4f6-63f457fc6613:
    tabs:
      -
        elements:
          -
            fieldUid: be53cbc6-0515-4f96-89e8-bd2d6e7b7b8b # Tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  be53cbc6-0515-4f96-89e8-bd2d6e7b7b8b: # Tekst
    contentColumnType: text
    fieldGroup: null
    handle: tekst
    instructions: ''
    name: Tekst
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: textVolleBreedte
name: 'Text volle breedte'
sortOrder: 3
