fieldLayouts:
  ad749777-2a8a-4073-a8cc-2289175fb7dd:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 66f2a356-452a-4990-9704-8c0c3b914b31
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 95a5a802-87c8-46a8-b7dd-5784f30fa86e
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 1
handle: homepage
hasTitleField: false
name: Homepage
section: 5a740624-0788-4b14-b14f-72fc4a6389ed
sortOrder: 1
titleFormat: '{section.name|raw}'
