fieldLayouts:
  ad749777-2a8a-4073-a8cc-2289175fb7dd:
    tabs:
      -
        elements:
          -
            fieldUid: c60c2474-7439-41cd-85f5-6e4cae7dd248 # Contentbuilder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: Test
            label: ''
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 66f2a356-452a-4990-9704-8c0c3b914b31
            instructions: 'Hier plaats je een handleiding voor dit veld'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 95a5a802-87c8-46a8-b7dd-5784f30fa86e
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
handle: home
hasTitleField: false
name: Home
section: 5a740624-0788-4b14-b14f-72fc4a6389ed # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
