handle: hoofdmenu
instructions: ''
maxNodes: ''
name: Hoofdmenu
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  custom:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: ''
propagateNodes: false
siteSettings:
  e09dcfda-5dae-4bd5-92ee-a0461898e1ef: null
sortOrder: 1
structure:
  maxLevels: null
  uid: acfb0931-dade-4628-9b60-675834772149
