contentColumnType: text
fieldGroup: b4ee02ab-2d5a-4cf0-b6c8-b521bf42b1f4
handle: mobielNummer
instructions: ''
name: 'Mobiel nummer'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
