contentColumnType: text
fieldGroup: 0ca941e9-ca9f-45d8-9f2a-2a85702d781f
handle: paginaTitel
instructions: ''
name: 'Pagina Titel'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
