contentColumnType: string(255)
fieldGroup: b4ee02ab-2d5a-4cf0-b6c8-b521bf42b1f4
handle: pinterestUrl
instructions: ''
name: 'Pinterest URL'
searchable: true
settings:
  maxLength: '255'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
