dateModified: 1619684036
email:
  fromEmail: beheer@vormenvorm.nl
  fromName: 'Basis Raaktinvorm'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '1.2'
  navigation:
    edition: standard
    enabled: true
    licenseKey: WL5FI4O4DXBA02S3Z24ZL2NU
    schemaVersion: 1.0.21
    settings:
      bypassProjectConfig: false
      pluginName: Navigatie
      propagateSiteElements: true
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  sitemap:
    edition: standard
    enabled: true
    schemaVersion: 1.0.2
  sprout-forms:
    enabled: true
    schemaVersion: 3.11.8
    settings:
      captchaSettings:
        __assoc__:
          -
            - barrelstrength\sproutforms\captchas\DuplicateCaptcha
            -
              __assoc__:
                -
                  - enabled
                  - 1
          -
            - barrelstrength\sproutforms\captchas\JavascriptCaptcha
            -
              __assoc__:
                -
                  - enabled
                  - 1
          -
            - barrelstrength\sproutforms\captchas\HoneypotCaptcha
            -
              __assoc__:
                -
                  - enabled
                  - 1
                -
                  - honeypotFieldName
                  - beesknees
                -
                  - honeypotScreenReaderMessage
                  - 'Leave this field blank'
      cleanupProbability: 1000
      defaultSection: entries
      enableEditFormEntryViaFrontEnd: ''
      enableSaveData: '1'
      enableSaveDataDefaultValue: '1'
      formTemplateId: barrelstrength\sproutforms\formtemplates\AccessibleTemplates
      pluginNameOverride: Formulieren
      saveSpamToDatabase: ''
      showNotificationsTab: true
      showReportsTab: true
      spamLimit: 500
      spamRedirectBehavior: redirectAsNormal
      trackRemoteIp: ''
  sprout-forms-google-recaptcha:
    edition: standard
    enabled: true
    schemaVersion: 1.1.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  wordsmith:
    edition: standard
    enabled: true
    schemaVersion: 0.0.0.0
system:
  edition: pro
  live: true
  name: 'Basis Vorm & Vorm'
  schemaVersion: 3.6.8
  timeZone: Europe/Amsterdam
