dateModified: 1624966876
email:
  fromEmail: beheer@vormenvorm.nl
  fromName: 'Basis Raaktinvorm'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '1.2'
  formie:
    edition: standard
    enabled: true
    licenseKey: JXQHQ7GKXW8L1NI9G11XMFC7
    schemaVersion: 1.1.11
    settings:
      ajaxTimeout: 10
      alertEmails: null
      defaultDateDisplayType: ''
      defaultDateTime: null
      defaultDateValueOption: ''
      defaultEmailTemplate: ''
      defaultFileUploadVolume: ''
      defaultFormTemplate: ''
      defaultInstructionsPosition: verbb\formie\positions\AboveInput
      defaultLabelPosition: verbb\formie\positions\AboveInput
      defaultPage: forms
      enableUnloadWarning: true
      maxIncompleteSubmissionAge: 30
      maxSentNotificationsAge: 30
      pluginName: Formulieren
      saveSpam: true
      sendEmailAlerts: false
      sentNotifications: true
      spamBehaviour: showSuccess
      spamBehaviourMessage: ''
      spamKeywords: ''
      spamLimit: 500
      useQueueForIntegrations: true
      useQueueForNotifications: true
  navigation:
    edition: standard
    enabled: true
    licenseKey: WL5FI4O4DXBA02S3Z24ZL2NU
    schemaVersion: 1.0.21
    settings:
      bypassProjectConfig: false
      pluginName: 'Menu''s'
      propagateSiteElements: true
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  wordsmith:
    edition: standard
    enabled: true
    schemaVersion: 0.0.0.0
system:
  edition: pro
  live: true
  name: 'Basis Vorm & Vorm'
  schemaVersion: 3.6.8
  timeZone: Europe/Amsterdam
