enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  e09dcfda-5dae-4bd5-92ee-a0461898e1ef:
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
