enableVersioning: true
handle: privacyVerklaring
name: 'Privacy verklaring'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e09dcfda-5dae-4bd5-92ee-a0461898e1ef:
    enabledByDefault: true
    hasUrls: true
    template: pages/content.twig
    uriFormat: privacy-verklaring
type: single
